title: Suen Wang
position: Ph.D.  
affiliation: Affiliated Researcher (Copenhagen Business School)
email: swa.msc@cbs.dk
keywords: minimal academic
avatar: ./assets\img\DSC_6981.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

