title: Suen Wang
position: Ph.D.  
affiliation: Affiliated Researcher (Copenhagen Business School)
email: swa.msc@cbs.dk
keywords: political science 
avatar: ./assets\img\DSC_6981.jpg
google_analytics: G-ET267TEQJ2
favicon: ./assets/img/favicon2.png
favicon_dark: ./assets/img/favicon2.png
description: Suen's personal website
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

