title: Suen Wang Ph.D.
position: Assistant Professor (Politics and Society)
affiliation: Aalborg University
email: suwa@dps.aau.dk
keywords: Suen Wang 
avatar: ./assets\img\DSC_6981.jpg
google_analytics: G-853E2BS07F
favicon: ./assets/img/favicon2.png
favicon_dark: ./assets/img/favicon2.png
description: Suen Wang, Ph.D. Copenhagen Business School